version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - postgres_network
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/src
      - ./migrations:/app/migrations
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - postgres_network

volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge