"""empty message

Revision ID: 88d0f0e5c1e7
Revises: 
Create Date: 2024-01-14 01:03:52.803656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d0f0e5c1e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Enum('Agent', 'Captain, Information', 'Captain, Training', 'Captain, Safety', 'Captain, Control', 'Captain, Disciplinary', name='ranks_emum'), nullable=False))

    with op.batch_alter_table('agent_ability_association', schema=None) as batch_op:
        batch_op.alter_column('agent_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_ability_association', schema=None) as batch_op:
        batch_op.alter_column('agent_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('abilities', schema=None) as batch_op:
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
